CREATE DATABASE Curso;

CREATE TABLE Aluno 
(
	ra INT(30) NOT NULL AUTO_INCREMENT,
	nome VARCHAR(100) NOT NULL,
	idade INT(11) NOT NULL,
	cpf VARCHAR(14) NOT NULL,
	sexo VARCHAR(100) NOT NULL,
	PRIMARY KEY(ra)
);

CREATE TABLE Professor
(
	siape INT(30) NOT NULL AUTO_INCREMENT,
	nome VARCHAR(100) NOT NULL,
	idade INT(11) NOT NULL,
	cpf VARCHAR(14) NOT NULL,
	sexo VARCHAR(100) NOT NULL,
	PRIMARY KEY(siape)
);
